// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/cache/objectbox_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4136769240369754063),
      name: 'Preferences',
      lastPropertyId: const obx_int.IdUid(11, 5823573503151403325),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7298576750242691327),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2564764035305752386),
            name: 'tokenType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6004212513082920327),
            name: 'token',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8747023862093372666),
            name: 'identity',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5538667765775861981),
            name: 'cookies',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6041752930736553996),
            name: 'cookiesMap',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5460091695335542471),
            name: 'isOnboardingVisited',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3097786153875565344),
            name: 'otp',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2016319666089929569),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7518022613539333854),
            name: 'language',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5823573503151403325),
            name: 'theme',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 4136769240369754063),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Preferences: obx_int.EntityDefinition<Preferences>(
        model: _entities[0],
        toOneRelations: (Preferences object) => [],
        toManyRelations: (Preferences object) => {},
        getId: (Preferences object) => object.id,
        setId: (Preferences object, int id) {
          object.id = id;
        },
        objectToFB: (Preferences object, fb.Builder fbb) {
          final tokenTypeOffset = object.tokenType == null
              ? null
              : fbb.writeString(object.tokenType!);
          final tokenOffset =
              object.token == null ? null : fbb.writeString(object.token!);
          final identityOffset = object.identity == null
              ? null
              : fbb.writeString(object.identity!);
          final cookiesOffset =
              object.cookies == null ? null : fbb.writeString(object.cookies!);
          final cookiesMapOffset = object.cookiesMap == null
              ? null
              : fbb.writeListInt8(object.cookiesMap!);
          final otpOffset =
              object.otp == null ? null : fbb.writeString(object.otp!);
          final phoneOffset =
              object.phone == null ? null : fbb.writeString(object.phone!);
          final languageOffset = object.language == null
              ? null
              : fbb.writeString(object.language!);
          final themeOffset =
              object.theme == null ? null : fbb.writeString(object.theme!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, tokenTypeOffset);
          fbb.addOffset(2, tokenOffset);
          fbb.addOffset(3, identityOffset);
          fbb.addOffset(4, cookiesOffset);
          fbb.addOffset(5, cookiesMapOffset);
          fbb.addBool(6, object.isOnboardingVisited);
          fbb.addOffset(7, otpOffset);
          fbb.addOffset(8, phoneOffset);
          fbb.addOffset(9, languageOffset);
          fbb.addOffset(10, themeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final tokenParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final identityParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final cookiesParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final cookiesMapParam =
              const fb.ListReader<int>(fb.Int8Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final isOnboardingVisitedParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 16);
          final otpParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final tokenTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final languageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final themeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final object = Preferences(
              id: idParam,
              token: tokenParam,
              identity: identityParam,
              cookies: cookiesParam,
              cookiesMap: cookiesMapParam,
              isOnboardingVisited: isOnboardingVisitedParam,
              otp: otpParam,
              phone: phoneParam,
              tokenType: tokenTypeParam,
              language: languageParam,
              theme: themeParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Preferences] entity fields to define ObjectBox queries.
class Preferences_ {
  /// See [Preferences.id].
  static final id =
      obx.QueryIntegerProperty<Preferences>(_entities[0].properties[0]);

  /// See [Preferences.tokenType].
  static final tokenType =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[1]);

  /// See [Preferences.token].
  static final token =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[2]);

  /// See [Preferences.identity].
  static final identity =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[3]);

  /// See [Preferences.cookies].
  static final cookies =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[4]);

  /// See [Preferences.cookiesMap].
  static final cookiesMap =
      obx.QueryByteVectorProperty<Preferences>(_entities[0].properties[5]);

  /// See [Preferences.isOnboardingVisited].
  static final isOnboardingVisited =
      obx.QueryBooleanProperty<Preferences>(_entities[0].properties[6]);

  /// See [Preferences.otp].
  static final otp =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[7]);

  /// See [Preferences.phone].
  static final phone =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[8]);

  /// See [Preferences.language].
  static final language =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[9]);

  /// See [Preferences.theme].
  static final theme =
      obx.QueryStringProperty<Preferences>(_entities[0].properties[10]);
}
